let a = 5;
let b = 10;

let soma = a + b;
console.log ("A soma é " + (a+b));

let subtracao = a - b;
console.log ('subtracao:' + (a-b));

let divisao = a / b;
console.log = ('divisão: ' + (a/b))

let multiplicacao = a * b;
console.log ('multiplicação: ' (a*b))


if (a > b) {
    console.log = (" 'a' é maior que 'b'")
}
else {
    console.log = ("'b' é menor que 'a'")
}

const a = 5;
const b = 7
const b = 9

if (a > b && a > c) {
    console.log("O maior número é" + a + 'a')
}
if (b > a  && b > c) {
    console.log("O maior número é" + b + 'b')
}
else {
    console.log("O maior número é" + c + 'c')
}